# config.yaml

defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
hydra:  
  output_subdir: null  
  run:  
    dir: .
config_filename: null
data_dir: null
data_filename: null
data_ext: ".mp4"
landmarks_dir: null
landmarks_filename: null
landmarks_ext: ".pkl"
labels_filename: null
detector: retinaface
dst_filename: null
gpu_idx: 0
output_subdir: null
voice_sample_path: null  # path to voice sample WAV file for TTS cloning (optional)
tts_speaker: "alloy"  # OpenAI TTS voice: alloy, echo, fable, onyx, nova, shimmer
camera_index: 0  # camera device index (0=built-in, 1=iPhone via Continuity Camera, etc.)
