camera_index: 0
config_filename: ./configs/LRS3_V_WER19.1.ini
data_dir: null
data_ext: .mp4
data_filename: null
defaults:
- _self_
- override hydra/hydra_logging: disabled
- override hydra/job_logging: disabled
detector: mediapipe
dst_filename: null
gpu_idx: -1
hydra:
  output_subdir: null
  run:
    dir: .
labels_filename: null
landmarks_dir: null
landmarks_ext: .pkl
landmarks_filename: null
meeting_context: 'Medical device sales presentation. Products discussed include vaginal mesh, pelvic floor repair devices, and other surgical implants. Use proper medical terminology.'
output_subdir: null
persist_vector_db: true
tts_speaker: QxPbJa2ls7sQqs8Ra8Vz
voice_sample_path: null
